# Generated by Django 4.2.13 on 2024-07-10 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('img_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('Key_name', models.CharField(max_length=100)),
                ('provider_url', models.URLField(blank=True, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('kubeconfig_data', models.TextField(blank=True, null=True)),
                ('openStackuser', models.CharField(max_length=100, null=True)),
                ('tenant_name', models.CharField(max_length=100, null=True)),
                ('openstackpassword', models.CharField(max_length=100, null=True)),
                ('auth_url', models.URLField(null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('OpenShift_username', models.CharField(max_length=100, null=True)),
                ('OpenShift_password', models.CharField(max_length=100, null=True)),
                ('api_url', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('provider'), models.Model),
        ),
    ]
