# Generated by Django 4.2.13 on 2024-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_alter_cluster_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='k8s_key_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
